package com.PetClinic.model.enums;

public enum Speciality {

    NEUROLOGY, RADIOLOGY, ONCOLOGY, NUTRITION, DENTISTRY, DERMATOLOGY, CARDIOLOGY, EMERGENCY_AND_CRITICAL_CARE,
    SURGERY, OPHTHALMOLOGY, BEHAVIOR
}